CREATE TABLE POSTS (
    ID SERIAL PRIMARY KEY,
    USER_ID INTEGER NOT NULL,
    TITLE VARCHAR(255) NOT NULL,
    BODY TEXT NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (USER_ID)
      REFERENCES USERS (ID)
);
